"""CITATION.cff (Citation File Format 1.2.0) generated from note metadata."""
from __future__ import annotations

import datetime as dt

import yaml

from .common import ROOT, Note, write_text

CFF_SCHEMA_URL = "https://raw.githubusercontent.com/citation-file-format/citation-file-format/1.2.0/schema.json"


def _authors(note: Note) -> list[dict]:
    out = []
    for a in note.authors:
        entry = {"given-names": a["given_name"], "family-names": a["family_name"], "affiliation": a["affiliation"]}
        if a.get("orcid"):
            entry["orcid"] = f"https://orcid.org/{a['orcid']}"
        out.append(entry)
    return out


def _reference(note: Note) -> dict:
    d = dt.date.fromisoformat(note.date)
    ref = {
        "type": "report",
        "title": note.full_title,
        "authors": _authors(note),
        "institution": {"name": note.publisher},
        "collection-title": note.series_name,
        "number": note.number,
        "version": note.version,
        "date-published": d,
        "year": d.year,
        "month": d.month,
        "url": note.canonical_url,
        "repository-code": note.repo_url,
        "notes": f"{note.series_name} Note {note.number}, version {note.version}. Status: {note.meta['status']}.",
    }
    doi = note.doi()
    if doi:
        ref["doi"] = doi
    if note.license_granted:
        ref["license"] = note.license["spdx"]
    return ref


def build(notes: list[Note]) -> dict:
    """The latest note is the preferred citation; earlier notes are listed as references."""
    notes = sorted(notes, key=lambda n: n.number)
    latest = notes[-1]
    cff = {
        "cff-version": "1.2.0",
        "message": "If you refer to this work, please cite it using the preferred citation below.",
        "title": latest.full_title,
        "version": latest.version,
        "date-released": dt.date.fromisoformat(latest.date),
        "abstract": " ".join(latest.meta["abstract"].split()),
        "authors": _authors(latest),
        "keywords": latest.meta["keywords"],
        "repository-code": latest.repo_url,
        "url": latest.canonical_url,
    }
    doi = latest.doi()
    identifiers = []
    if doi:
        cff["doi"] = doi
        identifiers.append({"type": "doi", "value": doi,
                            "description": f"Archived record of {latest.series_name} Note {latest.number} v{latest.version}"})
    concept = latest.concept_doi()
    if concept and concept != doi:
        identifiers.append({"type": "doi", "value": concept,
                            "description": f"All versions of {latest.series_name} Note {latest.number} (resolves to the latest)"})
    if identifiers:
        cff["identifiers"] = identifiers
    if latest.license_granted:
        cff["license"] = latest.license["spdx"]
    cff["preferred-citation"] = _reference(latest)
    if len(notes) > 1:
        cff["references"] = [_reference(n) for n in notes[:-1]]
    return cff


def dump(cff: dict) -> str:
    header = ("# Generated by `python tools/publish.py build` from research/*/note.yaml.\n"
              "# Do not edit by hand. License and DOI fields appear only once granted / assigned.\n")
    return header + yaml.safe_dump(cff, sort_keys=False, allow_unicode=True, width=100)


def write(notes: list[Note]) -> None:
    write_text(ROOT / "CITATION.cff", dump(build(notes)))


def as_json_compatible(obj):
    """YAML dates -> ISO strings, for JSON Schema validation."""
    if isinstance(obj, dict):
        return {k: as_json_compatible(v) for k, v in obj.items()}
    if isinstance(obj, list):
        return [as_json_compatible(v) for v in obj]
    if isinstance(obj, (dt.date, dt.datetime)):
        return obj.isoformat()
    return obj
